project:
  type: website
  output-dir: docs

website:
  title: "Jagan Jacob"

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
    include-in-header: google-verification.html

editor: visual

    